### ISSUE TITLE
Licensing in more permissive terms?

### ISSUE THREAD

**Issue by allentiak** [mauricioszabo/fullstack-template#1]
Hi, Maurício,

This template code is to be freely used by everyone, as they see fit, right?
If so... Would you perhaps consider using a more permissive license for this template, such as Apache 2.0?

References:
[What license should I use for website maintenance system templates?](https://www.gnu.org/licenses/gpl-faq.en.html#WMS)
[How to Choose a License for Your Own Work](https://www.gnu.org/licenses/license-recommendations.html)
[How Many Open Source Licenses Do You Need?](https://www.datamation.com/open-source/bruce-perens-how-many-open-source-licenses-do-you-need/)

**Comment by mauricioszabo** [comment]
Fixed by this: ea46fe54a58424466c171362188a8b6e5216b0b5

It's now an MIT - No Attribution, so you can use and sub-license at will :)

**Comment by allentiak** [comment]
Thanks!

**Comment by allentiak** [comment]
BTW: You forgot to update the README...

**Comment by mauricioszabo** [comment]
Not anymore :)
